### ISSUE TITLE
Enhancement-Level Technical Debt

### ISSUE THREAD

**Issue by thewindsofwinter** [thewindsofwinter/titran#1]
**Duration:** approximately one to two engineer-days
**Objective:** Improve transpilation into Python with scoping of announcements. Make it possible to train a minimal neural network using only Titran (no interlaced python)
**Subtasks:**
 - [ ] Write logic for project scopes
 - [ ] Add additional commands (especially for imports)
 - [ ] Run a minimal 2-layer neural net on it and include in examples.
